#!/usr/bin/env python3
"""Generate contracts/topology_registry.yaml from network/mininet_test_topo.py."""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from network.mininet_test_topo import MyTopo  # noqa: E402

OUTPUT = PROJECT_ROOT / "contracts" / "topology_registry.yaml"
GENERATOR = "network/topology_builder.py"


def delay_ms(delay_str: str) -> float | None:
    if delay_str.endswith("ms"):
        return float(delay_str[:-2])
    return None


def main() -> None:
    topo = MyTopo()
    nodes: list[dict] = []
    links: list[dict] = []

    switch_ids = sorted({name for name in topo.nodes() if name.startswith("s")})
    host_ids = sorted({name for name in topo.nodes() if name.startswith("h")})

    for sid in switch_ids:
        nodes.append({"node_id": sid, "kind": "switch"})
    for hid in host_ids:
        nodes.append({"node_id": hid, "kind": "host", "role": "iot_sensor"})

    link_index = 1
    for node1, node2, info in topo.links(withInfo=True):
        if not (str(node1).startswith("s") and str(node2).startswith("s")):
            continue

        port1 = info.get("port1", 1)
        port2 = info.get("port2", 1)
        params = info.get("opts", {}) or {}
        bw = params.get("bw", 100)
        delay = params.get("delay", "10ms")

        link: dict = {
            "link_id": f"L{link_index}",
            "endpoint_a": {"node_id": str(node1), "port": port1},
            "endpoint_b": {"node_id": str(node2), "port": port2},
            "capacity_mbps": int(bw),
            "mininet_ifaces": [
                f"{node1}-eth{port1}",
                f"{node2}-eth{port2}",
            ],
        }
        configured = delay_ms(str(delay))
        if configured is not None:
            link["configured_delay_ms"] = configured

        links.append(link)
        link_index += 1

    doc = {
        "version": 1,
        "generated_by": GENERATOR,
        "nodes": nodes,
        "links": links,
    }

    header = (
        f"# Auto-generated by {GENERATOR} — do not hand-edit.\n"
        "# Regenerate whenever the Mininet topology changes:\n"
        f"#   python3 {GENERATOR}\n"
    )
    OUTPUT.write_text(header + yaml.safe_dump(doc, sort_keys=False), encoding="utf-8")
    print(f"Wrote {OUTPUT} ({len(nodes)} nodes, {len(links)} links)")


if __name__ == "__main__":
    main()
